---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oadp.openshift.io
  resources:
  - virtualmachinebackupsdiscoveries
  - virtualmachinefilerestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oadp.openshift.io
  resources:
  - virtualmachinebackupsdiscoveries/finalizers
  - virtualmachinefilerestores/finalizers
  verbs:
  - update
- apiGroups:
  - oadp.openshift.io
  resources:
  - virtualmachinebackupsdiscoveries/status
  - virtualmachinefilerestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - velero.io
  resources:
  - backups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - velero.io
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
