//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/migtools/oadp-vm-file-restore/api/v1alpha1/types"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryStatistics) DeepCopyInto(out *DiscoveryStatistics) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryStatistics.
func (in *DiscoveryStatistics) DeepCopy() *DiscoveryStatistics {
	if in == nil {
		return nil
	}
	out := new(DiscoveryStatistics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileServingInfo) DeepCopyInto(out *FileServingInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileServingInfo.
func (in *FileServingInfo) DeepCopy() *FileServingInfo {
	if in == nil {
		return nil
	}
	out := new(FileServingInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCRestoreInfo) DeepCopyInto(out *PVCRestoreInfo) {
	*out = *in
	out.PVCInfo = in.PVCInfo
	if in.Restores != nil {
		in, out := &in.Restores, &out.Restores
		*out = make([]RestoreInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCRestoreInfo.
func (in *PVCRestoreInfo) DeepCopy() *PVCRestoreInfo {
	if in == nil {
		return nil
	}
	out := new(PVCRestoreInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreInfo) DeepCopyInto(out *RestoreInfo) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreInfo.
func (in *RestoreInfo) DeepCopy() *RestoreInfo {
	if in == nil {
		return nil
	}
	out := new(RestoreInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupsDiscovery) DeepCopyInto(out *VirtualMachineBackupsDiscovery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupsDiscovery.
func (in *VirtualMachineBackupsDiscovery) DeepCopy() *VirtualMachineBackupsDiscovery {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupsDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineBackupsDiscovery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupsDiscoveryList) DeepCopyInto(out *VirtualMachineBackupsDiscoveryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineBackupsDiscovery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupsDiscoveryList.
func (in *VirtualMachineBackupsDiscoveryList) DeepCopy() *VirtualMachineBackupsDiscoveryList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupsDiscoveryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineBackupsDiscoveryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupsDiscoverySpec) DeepCopyInto(out *VirtualMachineBackupsDiscoverySpec) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(types.FlexibleTime)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(types.FlexibleTime)
		**out = **in
	}
	if in.RequestedBackups != nil {
		in, out := &in.RequestedBackups, &out.RequestedBackups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupsDiscoverySpec.
func (in *VirtualMachineBackupsDiscoverySpec) DeepCopy() *VirtualMachineBackupsDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupsDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBackupsDiscoveryStatus) DeepCopyInto(out *VirtualMachineBackupsDiscoveryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ValidBackups != nil {
		in, out := &in.ValidBackups, &out.ValidBackups
		*out = make([]types.VeleroBackupInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InvalidBackups != nil {
		in, out := &in.InvalidBackups, &out.InvalidBackups
		*out = make([]types.InvalidBackupInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackupDiscoveryProgress != nil {
		in, out := &in.BackupDiscoveryProgress, &out.BackupDiscoveryProgress
		*out = make([]types.BackupDiscoveryProgress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DiscoveryStats != nil {
		in, out := &in.DiscoveryStats, &out.DiscoveryStats
		*out = new(DiscoveryStatistics)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBackupsDiscoveryStatus.
func (in *VirtualMachineBackupsDiscoveryStatus) DeepCopy() *VirtualMachineBackupsDiscoveryStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBackupsDiscoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineFileRestore) DeepCopyInto(out *VirtualMachineFileRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineFileRestore.
func (in *VirtualMachineFileRestore) DeepCopy() *VirtualMachineFileRestore {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineFileRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineFileRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineFileRestoreList) DeepCopyInto(out *VirtualMachineFileRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineFileRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineFileRestoreList.
func (in *VirtualMachineFileRestoreList) DeepCopy() *VirtualMachineFileRestoreList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineFileRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineFileRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineFileRestoreSpec) DeepCopyInto(out *VirtualMachineFileRestoreSpec) {
	*out = *in
	if in.SelectedBackups != nil {
		in, out := &in.SelectedBackups, &out.SelectedBackups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineFileRestoreSpec.
func (in *VirtualMachineFileRestoreSpec) DeepCopy() *VirtualMachineFileRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineFileRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineFileRestoreStatus) DeepCopyInto(out *VirtualMachineFileRestoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FileServingInfo != nil {
		in, out := &in.FileServingInfo, &out.FileServingInfo
		*out = new(FileServingInfo)
		**out = **in
	}
	if in.PVCRestores != nil {
		in, out := &in.PVCRestores, &out.PVCRestores
		*out = make([]PVCRestoreInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineFileRestoreStatus.
func (in *VirtualMachineFileRestoreStatus) DeepCopy() *VirtualMachineFileRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineFileRestoreStatus)
	in.DeepCopyInto(out)
	return out
}
